In [1]:
import pandas as pd

In [ ]:
# Importar datos
products = pd.read_csv(r"C:\Users\bella\OneDrive\Escritorio\DATA SCIENCE\PF_Data_science\data\raw\olist_products_dataset.csv")
order_items = pd.read_csv(r"C:\Users\bella\OneDrive\Escritorio\DATA SCIENCE\PF_Data_science\data\raw\olist_order_items_dataset.csv")
orders = pd.read_csv(r"C:\Users\bella\OneDrive\Escritorio\DATA SCIENCE\PF_Data_science\data\raw\olist_orders_dataset.csv")
reviews = pd.read_csv(r"C:\Users\bella\OneDrive\Escritorio\DATA SCIENCE\PF_Data_science\data\raw\olist_order_reviews_dataset.csv")

In [ ]:
# Revición preliminar de Datos
print(products.columns)
print(order_items.columns)
print(orders.columns)
print(reviews.columns)

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')
Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')
Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [ ]:
# Número de productos Pet_shop
pet_products = products[products["product_category_name"] == "pet_shop"]
pet_products_count = pet_products["product_id"].nunique()

print("Productos únicos en pet_shop:", pet_products_count)

Productos únicos en pet_shop: 719

In [ ]:
#Número compras hay de productos de mascotas
pet_order_items = order_items.merge(
    pet_products[["product_id"]],
    on="product_id",
    how="inner"
)

pet_orders_count = pet_order_items["order_id"].nunique()

print("Órdenes con productos de mascotas:", pet_orders_count)

Órdenes con productos de mascotas: 1710

In [ ]:
# Número de reseñas
pet_reviews = reviews.merge(
    pet_order_items[["order_id"]].drop_duplicates(),
    on="order_id",
    how="inner"
)

pet_reviews_count = pet_reviews["review_id"].nunique()

print("Reseñas asociadas a compras de mascotas:", pet_reviews_count)

Reseñas asociadas a compras de mascotas: 1700

In [ ]:
# N° Clientes
pet_orders = orders.merge(
    pet_order_items[["order_id"]].drop_duplicates(),
    on="order_id",
    how="inner"
)

pet_customers_count = pet_orders["customer_id"].nunique()

print("Clientes únicos que compraron mascotas:", pet_customers_count)

Clientes únicos que compraron mascotas: 1710

In [ ]:
# ticket promedio
pet_ticket_avg = pet_order_items["price"].mean()

print("Precio promedio por ítem pet_shop:", pet_ticket_avg)

Precio promedio por ítem pet_shop: 110.0746841294299

In [ ]:
# Total de reseñas en categoria Pet Shop
total_pet_reviews = pet_reviews.shape[0]
total_pet_reviews_con_texto = (
    pet_reviews["review_comment_message"].notna() &
    (pet_reviews["review_comment_message"].str.strip() != "")
).sum()

print("Total de reseñas de pet_shop:", total_pet_reviews)
print("Total de reseñas de pet_shop con texto:", total_pet_reviews_con_texto)

Total de reseñas de pet_shop: 1703
Total de reseñas de pet_shop con texto: 650

In [ ]:
# Esplorar categorias y productos
categorias_productos = (
    products.dropna(subset=["product_category_name"])
    .groupby("product_category_name")["product_id"]
    .nunique()
    .reset_index(name="numero_productos")
    .sort_values(by="numero_productos", ascending=False)
)

categorias_productos

            product_category_name  numero_productos
13                cama_mesa_banho              3029
32                  esporte_lazer              2867
54               moveis_decoracao              2657
11                   beleza_saude              2444
72          utilidades_domesticas              2335
..                            ...               ...
15                casa_conforto_2                 5
37  fashion_roupa_infanto_juvenil                 5
60                       pc_gamer                 3
67             seguros_e_servicos                 2
17              cds_dvds_musicais                 1

[73 rows x 2 columns]

In [ ]:
# Top de catégorias
top_10_categorias = (
    products.dropna(subset=["product_category_name"])
    .groupby("product_category_name")["product_id"]
    .nunique()
    .reset_index(name="numero_productos")
    .sort_values(by="numero_productos", ascending=False)
    .head(10)
)

top_10_categorias

     product_category_name  numero_productos
13         cama_mesa_banho              3029
32           esporte_lazer              2867
54        moveis_decoracao              2657
11            beleza_saude              2444
72   utilidades_domesticas              2335
8               automotivo              1900
44  informatica_acessorios              1639
12              brinquedos              1411
66      relogios_presentes              1329
70               telefonia              1134

In [21]:
# Unir productos con items de orden
items_con_categoria = order_items.merge(
    products[["product_id", "product_category_name"]],
    on="product_id",
    how="left"
)

# Quitar categorías nulas
items_con_categoria = items_con_categoria.dropna(subset=["product_category_name"])

# Valor por orden y categoría
valor_orden_categoria = (
    items_con_categoria
    .groupby(["product_category_name", "order_id"])["price"]
    .sum()
    .reset_index(name="valor_orden_categoria")
)

# Ticket promedio por categoría
ticket_promedio_categoria = (
    valor_orden_categoria
    .groupby("product_category_name")["valor_orden_categoria"]
    .mean()
    .reset_index(name="ticket_promedio")
    .sort_values(by="ticket_promedio", ascending=False)
)

In [8]:
print(ticket_promedio_categoria.to_string(index=False))

                         product_category_name  ticket_promedio
                                           pcs      1231.840497
                   portateis_casa_forno_e_cafe       632.609467
                            eletrodomesticos_2       484.263846
                     agro_industria_e_comercio       398.519066
                         instrumentos_musicais       304.934522
                               eletroportateis       302.616794
 portateis_cozinha_e_preparadores_de_alimentos       283.466429
                                telefonia_fixa       274.576037
              construcao_ferramentas_seguranca       242.781557
                                  climatizacao       217.489960
                             moveis_escritorio       215.208720
                            relogios_presentes       214.261323
                                 moveis_quarto       210.829263
             construcao_ferramentas_construcao       193.419238
                                      pc_gamer       193.243750
moveis_cozinha_area_de_servico_jantar_e_jardim       186.807944
                                    cool_stuff       174.914882
                               casa_construcao       169.567592
                 industria_comercio_e_negocios       168.806851
             construcao_ferramentas_iluminacao       168.360656
            construcao_ferramentas_ferramentas       163.958247
                                   moveis_sala       163.309384
                                        musica       158.798684
                                    la_cuisine       158.076154
                       sinalizacao_e_seguranca       153.637357
                                    automotivo       152.096513
                                consoles_games       148.272335
                                 casa_conforto       147.536625
                                         audio       144.824286
                                         bebes       142.726132
                                  beleza_saude       142.449224
                            seguros_e_servicos       141.645000
                            ferramentas_jardim       137.935321
                        informatica_acessorios       136.336421
                              malas_acessorios       135.812360
                 construcao_ferramentas_jardim       132.556134
                                 esporte_lazer       127.985618
                                    perfumaria       126.225449
                                      pet_shop       125.330649
                                    brinquedos       124.535924
                                         artes       119.815050
                             artigos_de_festas       115.004615
                     moveis_colchao_e_estofado       114.949474
                              moveis_decoracao       113.159015
                               cama_mesa_banho       110.118794
                         utilidades_domesticas       107.452186
                                     cine_foto       106.668615
                              eletrodomesticos       104.936558
                                  dvds_blu_ray       101.684576
                                  market_place       101.351679
                                     papelaria        99.932164
                              fashion_calcados        98.178208
                       fashion_roupa_masculina        96.409107
                      tablets_impressao_imagem        95.296329
                        livros_interesse_geral        91.517344
                             livros_importados        87.544340
                   fashion_bolsas_e_acessorios        81.986878
                            artes_e_artesanato        78.870000
                fashion_underwear_e_moda_praia        78.855785
                               fashion_esporte        78.500370
                                     telefonia        77.082050
                                       bebidas        75.517508
                               livros_tecnicos        73.446385
                        fashion_roupa_feminina        71.888205
                 fashion_roupa_infanto_juvenil        71.231250
                              artigos_de_natal        68.756406
                             alimentos_bebidas        66.869956
                                     alimentos        65.318689
                                   eletronicos        62.841859
                             cds_dvds_musicais        60.833333
                               fraldas_higiene        58.058889
                                        flores        38.277241
                               casa_conforto_2        31.677917

In [ ]:
# Relación Catégoria Porductos y Ticket
resumen_categorias = categorias_productos.merge(
    ticket_promedio_categoria,
    on="product_category_name",
    how="left"
).sort_values(by="numero_productos", ascending=False)

resumen_categorias

            product_category_name  numero_productos  ticket_promedio
0                 cama_mesa_banho              3029       110.118794
1                   esporte_lazer              2867       127.985618
2                moveis_decoracao              2657       113.159015
3                    beleza_saude              2444       142.449224
4           utilidades_domesticas              2335       107.452186
..                            ...               ...              ...
68                casa_conforto_2                 5        31.677917
69  fashion_roupa_infanto_juvenil                 5        71.231250
70                       pc_gamer                 3       193.243750
71             seguros_e_servicos                 2       141.645000
72              cds_dvds_musicais                 1        60.833333

[73 rows x 3 columns]

In [ ]:
# top 60 de Productos y ticket
resumen_categorias_top20 = (
    categorias_productos.merge(
        ticket_promedio_categoria,
        on="product_category_name",
        how="left"
    )
    .rename(columns={
        "product_category_name": "categoria",
        "numero_productos": "numero_productos",
        "ticket_promedio": "ticket_promedio"
    })
    .sort_values(by="numero_productos", ascending=False)
    .head(60)
    .reset_index(drop=True)
)

resumen_categorias_top20.index = resumen_categorias_top20.index + 1
resumen_categorias_top20["ticket_promedio"] = resumen_categorias_top20["ticket_promedio"].round(2)

resumen_categorias_top20

,categoria,numero_productos,ticket_promedio
1,cama_mesa_banho,3029,110.12
2,esporte_lazer,2867,127.99
3,moveis_decoracao,2657,113.16
4,beleza_saude,2444,142.45
5,utilidades_domesticas,2335,107.45
6,automotivo,1900,152.10
7,informatica_acessorios,1639,136.34
8,brinquedos,1411,124.54
9,relogios_presentes,1329,214.26
10,telefonia,1134,77.08
11,bebes,919,142.73
12,perfumaria,868,126.23
13,papelaria,849,99.93
14,fashion_bolsas_e_acessorios,849,81.99
15,cool_stuff,789,174.91
16,ferramentas_jardim,753,137.94
17,pet_shop,719,125.33
18,eletronicos,517,62.84
19,construcao_ferramentas_construcao,400,193.42
20,eletrodomesticos,370,104.94
21,malas_acessorios,349,135.81
22,consoles_games,317,148.27
23,moveis_escritorio,309,215.21
24,instrumentos_musicais,289,304.93
25,eletroportateis,231,302.62
26,casa_construcao,225,169.57
27,livros_interesse_geral,216,91.52
28,fashion_calcados,173,98.18
29,moveis_sala,156,163.31
30,climatizacao,124,217.49
31,livros_tecnicos,123,73.45
32,telefonia_fixa,116,274.58
33,casa_conforto,111,147.54
34,market_place,104,101.35
35,alimentos_bebidas,104,66.87
36,fashion_roupa_masculina,95,96.41
37,moveis_cozinha_area_de_servico_jantar_e_jardim,94,186.81
38,sinalizacao_e_seguranca,93,153.64
39,construcao_ferramentas_seguranca,91,242.78
40,eletrodomesticos_2,90,484.26
41,construcao_ferramentas_jardim,88,132.56
42,alimentos,82,65.32
43,bebidas,81,75.52
44,construcao_ferramentas_iluminacao,78,168.36
45,agro_industria_e_comercio,74,398.52
46,industria_comercio_e_negocios,68,168.81
47,artigos_de_natal,65,68.76
48,audio,58,144.82
49,artes,55,119.82
50,fashion_underwear_e_moda_praia,53,78.86
51,dvds_blu_ray,48,101.68
52,moveis_quarto,45,210.83
53,construcao_ferramentas_ferramentas,39,163.96
54,livros_importados,31,87.54
55,portateis_casa_forno_e_cafe,31,632.61
56,pcs,30,1231.84
57,cine_foto,28,106.67
58,fashion_roupa_feminina,27,71.89
59,musica,27,158.80
60,artigos_de_festas,26,115.00

In [15]:
# Diccionario de agrupación
mapa_grupos = {
    "cama_mesa_banho": "Hogar y decoracion",
    "moveis_decoracao": "Hogar y decoracion",
    "utilidades_domesticas": "Hogar y decoracion",
    "casa_conforto": "Hogar y decoracion",
    "moveis_sala": "Hogar y decoracion",

    "beleza_saude": "Belleza, salud y accesorios personales",
    "perfumaria": "Belleza, salud y accesorios personales",
    "fashion_bolsas_e_acessorios": "Belleza, salud y accesorios personales",
    "fashion_calcados": "Belleza, salud y accesorios personales",
    "relogios_presentes": "Belleza, salud y accesorios personales",

    "informatica_acessorios": "Tecnologia y entretenimiento",
    "telefonia": "Tecnologia y entretenimiento",
    "eletronicos": "Tecnologia y entretenimiento",
    "consoles_games": "Tecnologia y entretenimiento",
    "cool_stuff": "Tecnologia y entretenimiento",

    "bebes": "Familia, mascotas y recreacion",
    "brinquedos": "Familia, mascotas y recreacion",
    "pet_shop": "Familia, mascotas y recreacion",
    "papelaria": "Familia, mascotas y recreacion",
    "esporte_lazer": "Familia, mascotas y recreacion"
}

# Crear columna de grupo
products["grupo_categoria"] = products["product_category_name"].map(mapa_grupos)

# Ver resultado
products[["product_id", "product_category_name", "grupo_categoria"]].head(20)

,product_id,product_category_name,grupo_categoria
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,"Belleza, salud y accesorios personales"
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,NaN
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,"Familia, mascotas y recreacion"
3,cef67bcfe19066a932b7673e239eb23d,bebes,"Familia, mascotas y recreacion"
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,Hogar y decoracion
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,NaN
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,Tecnologia y entretenimiento
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,Hogar y decoracion
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,NaN
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,"Familia, mascotas y recreacion"
10,14aa47b7fe5c25522b47b4b29c98dcb9,cama_mesa_banho,Hogar y decoracion
11,03b63c5fc16691530586ae020c345514,bebes,"Familia, mascotas y recreacion"
12,cf55509ea8edaaac1d28fdb16e48fc22,instrumentos_musicais,NaN
13,7bb6f29c2be57716194f96496660c7c2,moveis_decoracao,Hogar y decoracion
14,eb31436580a610f202c859463d8c7415,construcao_ferramentas_seguranca,NaN
15,3bb7f144022e6732727d8d838a7b13b3,esporte_lazer,"Familia, mascotas y recreacion"
16,6a2fb4dd53d2cdb88e0432f1284a004c,perfumaria,"Belleza, salud y accesorios personales"
17,a1b71017a84f92fd8da4aeefba108a24,informatica_acessorios,Tecnologia y entretenimiento
18,a0736b92e52f6cead290e30b578413b6,moveis_decoracao,Hogar y decoracion
19,f53103a77d9cf245e579ea37e5ec51f0,cama_mesa_banho,Hogar y decoracion

In [ ]:
# Total Productos por Grupo
productos_por_grupo = (
    products.dropna(subset=["grupo_categoria"])
    .groupby("grupo_categoria")["product_id"]
    .nunique()
    .reset_index(name="numero_productos")
    .sort_values(by="numero_productos", ascending=False)
)

productos_por_grupo

                          grupo_categoria  numero_productos
2                      Hogar y decoracion              8288
1          Familia, mascotas y recreacion              6765
0  Belleza, salud y accesorios personales              5663
3            Tecnologia y entretenimiento              4396

In [ ]:
# Categoría de producto y grupo 
categorias_con_grupo = (
    products[["product_category_name", "grupo_categoria"]]
    .dropna(subset=["grupo_categoria"])
    .drop_duplicates()
    .sort_values(by=["grupo_categoria", "product_category_name"])
    .reset_index(drop=True)
)

categorias_con_grupo

          product_category_name                         grupo_categoria
0                  beleza_saude  Belleza, salud y accesorios personales
1   fashion_bolsas_e_acessorios  Belleza, salud y accesorios personales
2              fashion_calcados  Belleza, salud y accesorios personales
3                    perfumaria  Belleza, salud y accesorios personales
4            relogios_presentes  Belleza, salud y accesorios personales
5                         bebes          Familia, mascotas y recreacion
6                    brinquedos          Familia, mascotas y recreacion
7                 esporte_lazer          Familia, mascotas y recreacion
8                     papelaria          Familia, mascotas y recreacion
9                      pet_shop          Familia, mascotas y recreacion
10              cama_mesa_banho                      Hogar y decoracion
11                casa_conforto                      Hogar y decoracion
12             moveis_decoracao                      Hogar y decoracion
13                  moveis_sala                      Hogar y decoracion
14        utilidades_domesticas                      Hogar y decoracion
15               consoles_games            Tecnologia y entretenimiento
16                   cool_stuff            Tecnologia y entretenimiento
17                  eletronicos            Tecnologia y entretenimiento
18       informatica_acessorios            Tecnologia y entretenimiento
19                    telefonia            Tecnologia y entretenimiento

In [ ]:
# Grupo y ticket
items_con_grupo = order_items.merge(
    products[["product_id", "product_category_name", "grupo_categoria"]],
    on="product_id",
    how="left"
)

items_con_grupo = items_con_grupo.dropna(subset=["grupo_categoria"])

valor_orden_grupo = (
    items_con_grupo
    .groupby(["grupo_categoria", "order_id"])["price"]
    .sum()
    .reset_index(name="valor_orden_grupo")
)

ticket_promedio_grupo = (
    valor_orden_grupo
    .groupby("grupo_categoria")["valor_orden_grupo"]
    .mean()
    .reset_index(name="ticket_promedio_grupo")
    .sort_values(by="ticket_promedio_grupo", ascending=False)
)

ticket_promedio_grupo["ticket_promedio_grupo"] = ticket_promedio_grupo["ticket_promedio_grupo"].round(2)

ticket_promedio_grupo

                          grupo_categoria  ticket_promedio_grupo
0  Belleza, salud y accesorios personales                 154.20
1          Familia, mascotas y recreacion                 126.03
3            Tecnologia y entretenimiento                 120.88
2                      Hogar y decoracion                 112.80

In [ ]:
# Resumen
resumen_grupos = productos_por_grupo.merge(
    ticket_promedio_grupo,
    on="grupo_categoria",
    how="left"
)

resumen_grupos

,grupo_categoria,numero_productos,ticket_promedio_grupo
0,Hogar y decoracion,8288,112.80
1,"Familia, mascotas y recreacion",6765,126.03
2,"Belleza, salud y accesorios personales",5663,154.20
3,Tecnologia y entretenimiento,4396,120.88